### ISSUE TITLE
Are you serious?

### ISSUE THREAD

**Issue by THEG77** [python-cplusplus-java/discord-nitro-emojiis#1]

**Comment by python-cplusplus-java** [comment]
yes i am!
how may i help you?

**Comment by THEG77** [comment]
Yeah i tried it... it gets the link to the text box but I am unable to send it... Discord Checks Maybe.

**Comment by python-cplusplus-java** [comment]
ohhh yeah, i realized its not able to send in 99% of cases so i changed it to alert with the link, but i forgot to push the new version.

Sorry about that, ill be better with pushing and pulling in furture
(its up now)
