### ISSUE TITLE
Still doesn't work.

### ISSUE THREAD

**Issue by THEG77** [python-cplusplus-java/discord-nitro-emojiis#2]
As you added the warn thingy it asks it click ok but that does nothing :/

**Comment by python-cplusplus-java** [comment]
It warns you with a link, if you copy and paste that link into the message box it will send the emojii

**Comment by python-cplusplus-java** [comment]
is the issue resolved? And should i close it

**Comment by THEG77** [comment]
Yup worked good in some servers that allowed embeds 👍
